version: 2.1
jobs:
  build:
    executor:
      name: node/default
      tag: '14.15.1'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn prepare:rinkeby
          name: Create Subgraph Yaml for Rinkeby
      - run:
          command: yarn codegen
          name: Create Types
      - run:
          command: yarn build
          name: Build
orbs:
  node: circleci/node@4.1.0
workflows:
  build_subgraph:
    jobs:
      - build:
          pre-steps:
            - run:
                command: echo "registry=https://registry.npmjs.org/" > ~/.npmrc && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc